/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.Protocol.GrowingObject;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GetChangeAnnotations extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6263137799368980001L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GetChangeAnnotations\",\"namespace\":\"Energistics.Etp.v12.Protocol.GrowingObject\",\"fields\":[{\"name\":\"sinceChangeTime\",\"type\":\"long\"},{\"name\":\"uris\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"latestOnly\",\"type\":\"boolean\",\"default\":false}],\"protocol\":\"6\",\"messageType\":\"19\",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GetChangeAnnotations> ENCODER =
      new BinaryMessageEncoder<GetChangeAnnotations>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GetChangeAnnotations> DECODER =
      new BinaryMessageDecoder<GetChangeAnnotations>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GetChangeAnnotations> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GetChangeAnnotations> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GetChangeAnnotations> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GetChangeAnnotations>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GetChangeAnnotations to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GetChangeAnnotations from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GetChangeAnnotations instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GetChangeAnnotations fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long sinceChangeTime;
   private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> uris;
   private boolean latestOnly;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GetChangeAnnotations() {}

  /**
   * All-args constructor.
   * @param sinceChangeTime The new value for sinceChangeTime
   * @param uris The new value for uris
   * @param latestOnly The new value for latestOnly
   */
  public GetChangeAnnotations(java.lang.Long sinceChangeTime, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> uris, java.lang.Boolean latestOnly) {
    this.sinceChangeTime = sinceChangeTime;
    this.uris = uris;
    this.latestOnly = latestOnly;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sinceChangeTime;
    case 1: return uris;
    case 2: return latestOnly;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sinceChangeTime = (java.lang.Long)value$; break;
    case 1: uris = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 2: latestOnly = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sinceChangeTime' field.
   * @return The value of the 'sinceChangeTime' field.
   */
  public long getSinceChangeTime() {
    return sinceChangeTime;
  }


  /**
   * Sets the value of the 'sinceChangeTime' field.
   * @param value the value to set.
   */
  public void setSinceChangeTime(long value) {
    this.sinceChangeTime = value;
  }

  /**
   * Gets the value of the 'uris' field.
   * @return The value of the 'uris' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getUris() {
    return uris;
  }


  /**
   * Sets the value of the 'uris' field.
   * @param value the value to set.
   */
  public void setUris(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.uris = value;
  }

  /**
   * Gets the value of the 'latestOnly' field.
   * @return The value of the 'latestOnly' field.
   */
  public boolean getLatestOnly() {
    return latestOnly;
  }


  /**
   * Sets the value of the 'latestOnly' field.
   * @param value the value to set.
   */
  public void setLatestOnly(boolean value) {
    this.latestOnly = value;
  }

  /**
   * Creates a new GetChangeAnnotations RecordBuilder.
   * @return A new GetChangeAnnotations RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder newBuilder() {
    return new Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder();
  }

  /**
   * Creates a new GetChangeAnnotations RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GetChangeAnnotations RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder newBuilder(Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder other) {
    if (other == null) {
      return new Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder();
    } else {
      return new Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder(other);
    }
  }

  /**
   * Creates a new GetChangeAnnotations RecordBuilder by copying an existing GetChangeAnnotations instance.
   * @param other The existing instance to copy.
   * @return A new GetChangeAnnotations RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder newBuilder(Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations other) {
    if (other == null) {
      return new Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder();
    } else {
      return new Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder(other);
    }
  }

  /**
   * RecordBuilder for GetChangeAnnotations instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GetChangeAnnotations>
    implements org.apache.avro.data.RecordBuilder<GetChangeAnnotations> {

    private long sinceChangeTime;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> uris;
    private boolean latestOnly;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sinceChangeTime)) {
        this.sinceChangeTime = data().deepCopy(fields()[0].schema(), other.sinceChangeTime);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.uris)) {
        this.uris = data().deepCopy(fields()[1].schema(), other.uris);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.latestOnly)) {
        this.latestOnly = data().deepCopy(fields()[2].schema(), other.latestOnly);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing GetChangeAnnotations instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.sinceChangeTime)) {
        this.sinceChangeTime = data().deepCopy(fields()[0].schema(), other.sinceChangeTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uris)) {
        this.uris = data().deepCopy(fields()[1].schema(), other.uris);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.latestOnly)) {
        this.latestOnly = data().deepCopy(fields()[2].schema(), other.latestOnly);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'sinceChangeTime' field.
      * @return The value.
      */
    public long getSinceChangeTime() {
      return sinceChangeTime;
    }


    /**
      * Sets the value of the 'sinceChangeTime' field.
      * @param value The value of 'sinceChangeTime'.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder setSinceChangeTime(long value) {
      validate(fields()[0], value);
      this.sinceChangeTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sinceChangeTime' field has been set.
      * @return True if the 'sinceChangeTime' field has been set, false otherwise.
      */
    public boolean hasSinceChangeTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sinceChangeTime' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder clearSinceChangeTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'uris' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getUris() {
      return uris;
    }


    /**
      * Sets the value of the 'uris' field.
      * @param value The value of 'uris'.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder setUris(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.uris = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'uris' field has been set.
      * @return True if the 'uris' field has been set, false otherwise.
      */
    public boolean hasUris() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'uris' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder clearUris() {
      uris = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'latestOnly' field.
      * @return The value.
      */
    public boolean getLatestOnly() {
      return latestOnly;
    }


    /**
      * Sets the value of the 'latestOnly' field.
      * @param value The value of 'latestOnly'.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder setLatestOnly(boolean value) {
      validate(fields()[2], value);
      this.latestOnly = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'latestOnly' field has been set.
      * @return True if the 'latestOnly' field has been set, false otherwise.
      */
    public boolean hasLatestOnly() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'latestOnly' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.GrowingObject.GetChangeAnnotations.Builder clearLatestOnly() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GetChangeAnnotations build() {
      try {
        GetChangeAnnotations record = new GetChangeAnnotations();
        record.sinceChangeTime = fieldSetFlags()[0] ? this.sinceChangeTime : (java.lang.Long) defaultValue(fields()[0]);
        record.uris = fieldSetFlags()[1] ? this.uris : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[1]);
        record.latestOnly = fieldSetFlags()[2] ? this.latestOnly : (java.lang.Boolean) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GetChangeAnnotations>
    WRITER$ = (org.apache.avro.io.DatumWriter<GetChangeAnnotations>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GetChangeAnnotations>
    READER$ = (org.apache.avro.io.DatumReader<GetChangeAnnotations>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.sinceChangeTime);

    long size0 = this.uris.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, java.lang.CharSequence> e0: this.uris.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.CharSequence v0 = e0.getValue();
      out.writeString(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeBoolean(this.latestOnly);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sinceChangeTime = in.readLong();

      long size0 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.uris; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
        this.uris = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence k0 = null;
          k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
          java.lang.CharSequence v0 = null;
          v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
          m0.put(k0, v0);
        }
      }

      this.latestOnly = in.readBoolean();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sinceChangeTime = in.readLong();
          break;

        case 1:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.uris; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
            this.uris = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence k0 = null;
              k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
              java.lang.CharSequence v0 = null;
              v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
              m0.put(k0, v0);
            }
          }
          break;

        case 2:
          this.latestOnly = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










