/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.Datatypes.ChannelData;
@org.apache.avro.specific.AvroGenerated
public enum ChannelDataKind implements org.apache.avro.generic.GenericEnumSymbol<ChannelDataKind> {
  DateTime, ElapsedTime, MeasuredDepth, PassIndexedDepth, TrueVerticalDepth, typeBoolean, typeInt, typeLong, typeFloat, typeDouble, typeString, typeBytes  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ChannelDataKind\",\"namespace\":\"Energistics.Etp.v12.Datatypes.ChannelData\",\"symbols\":[\"DateTime\",\"ElapsedTime\",\"MeasuredDepth\",\"PassIndexedDepth\",\"TrueVerticalDepth\",\"typeBoolean\",\"typeInt\",\"typeLong\",\"typeFloat\",\"typeDouble\",\"typeString\",\"typeBytes\"],\"fullName\":\"Energistics.Etp.v12.Datatypes.ChannelData.ChannelDataKind\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
