/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.Datatypes.Object;
@org.apache.avro.specific.AvroGenerated
public enum ObjectChangeKind implements org.apache.avro.generic.GenericEnumSymbol<ObjectChangeKind> {
  insert, update, authorized, joined, unjoined, joinedSubscription, unjoinedSubscription  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ObjectChangeKind\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"insert\",\"update\",\"authorized\",\"joined\",\"unjoined\",\"joinedSubscription\",\"unjoinedSubscription\"],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ObjectChangeKind\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
