/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.Protocol.ChannelDataLoad;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TruncateChannels extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4757691895699889227L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TruncateChannels\",\"namespace\":\"Energistics.Etp.v12.Protocol.ChannelDataLoad\",\"fields\":[{\"name\":\"channels\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"TruncateInfo\",\"namespace\":\"Energistics.Etp.v12.Datatypes.ChannelData\",\"fields\":[{\"name\":\"channelId\",\"type\":\"long\"},{\"name\":\"newEndIndex\",\"type\":{\"type\":\"record\",\"name\":\"IndexValue\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"item\",\"type\":[\"null\",\"long\",\"double\",{\"type\":\"record\",\"name\":\"PassIndexedDepth\",\"namespace\":\"Energistics.Etp.v12.Datatypes.ChannelData\",\"fields\":[{\"name\":\"pass\",\"type\":\"long\"},{\"name\":\"direction\",\"type\":{\"type\":\"enum\",\"name\":\"PassDirection\",\"symbols\":[\"Up\",\"HoldingSteady\",\"Down\"],\"fullName\":\"Energistics.Etp.v12.Datatypes.ChannelData.PassDirection\",\"depends\":[]}},{\"name\":\"depth\",\"type\":\"double\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ChannelData.PassIndexedDepth\",\"depends\":[\"Energistics.Etp.v12.Datatypes.ChannelData.PassDirection\"]}]}],\"fullName\":\"Energistics.Etp.v12.Datatypes.IndexValue\",\"depends\":[\"Energistics.Etp.v12.Datatypes.ChannelData.PassIndexedDepth\"]}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo\",\"depends\":[\"Energistics.Etp.v12.Datatypes.IndexValue\"]}}}],\"protocol\":\"22\",\"messageType\":\"9\",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels\",\"depends\":[\"Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TruncateChannels> ENCODER =
      new BinaryMessageEncoder<TruncateChannels>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TruncateChannels> DECODER =
      new BinaryMessageDecoder<TruncateChannels>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TruncateChannels> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TruncateChannels> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TruncateChannels> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TruncateChannels>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TruncateChannels to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TruncateChannels from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TruncateChannels instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TruncateChannels fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo> channels;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TruncateChannels() {}

  /**
   * All-args constructor.
   * @param channels The new value for channels
   */
  public TruncateChannels(java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo> channels) {
    this.channels = channels;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return channels;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: channels = (java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'channels' field.
   * @return The value of the 'channels' field.
   */
  public java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo> getChannels() {
    return channels;
  }


  /**
   * Sets the value of the 'channels' field.
   * @param value the value to set.
   */
  public void setChannels(java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo> value) {
    this.channels = value;
  }

  /**
   * Creates a new TruncateChannels RecordBuilder.
   * @return A new TruncateChannels RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder newBuilder() {
    return new Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder();
  }

  /**
   * Creates a new TruncateChannels RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TruncateChannels RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder newBuilder(Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder other) {
    if (other == null) {
      return new Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder();
    } else {
      return new Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder(other);
    }
  }

  /**
   * Creates a new TruncateChannels RecordBuilder by copying an existing TruncateChannels instance.
   * @param other The existing instance to copy.
   * @return A new TruncateChannels RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder newBuilder(Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels other) {
    if (other == null) {
      return new Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder();
    } else {
      return new Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder(other);
    }
  }

  /**
   * RecordBuilder for TruncateChannels instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TruncateChannels>
    implements org.apache.avro.data.RecordBuilder<TruncateChannels> {

    private java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo> channels;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.channels)) {
        this.channels = data().deepCopy(fields()[0].schema(), other.channels);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing TruncateChannels instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.channels)) {
        this.channels = data().deepCopy(fields()[0].schema(), other.channels);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'channels' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo> getChannels() {
      return channels;
    }


    /**
      * Sets the value of the 'channels' field.
      * @param value The value of 'channels'.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder setChannels(java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo> value) {
      validate(fields()[0], value);
      this.channels = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'channels' field has been set.
      * @return True if the 'channels' field has been set, false otherwise.
      */
    public boolean hasChannels() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'channels' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannels.Builder clearChannels() {
      channels = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TruncateChannels build() {
      try {
        TruncateChannels record = new TruncateChannels();
        record.channels = fieldSetFlags()[0] ? this.channels : (java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TruncateChannels>
    WRITER$ = (org.apache.avro.io.DatumWriter<TruncateChannels>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TruncateChannels>
    READER$ = (org.apache.avro.io.DatumReader<TruncateChannels>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










