/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.Datatypes;
@org.apache.avro.specific.AvroGenerated
public enum AnyArrayType implements org.apache.avro.generic.GenericEnumSymbol<AnyArrayType> {
  arrayOfBoolean, arrayOfInt, arrayOfLong, arrayOfFloat, arrayOfDouble, arrayOfString, bytes  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AnyArrayType\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"symbols\":[\"arrayOfBoolean\",\"arrayOfInt\",\"arrayOfLong\",\"arrayOfFloat\",\"arrayOfDouble\",\"arrayOfString\",\"bytes\"],\"fullName\":\"Energistics.Etp.v12.Datatypes.AnyArrayType\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
