/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.Datatypes;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ArrayOfNullableInt extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6806377435641018761L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ArrayOfNullableInt\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":[\"null\",\"int\"]}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfNullableInt\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ArrayOfNullableInt> ENCODER =
      new BinaryMessageEncoder<ArrayOfNullableInt>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ArrayOfNullableInt> DECODER =
      new BinaryMessageDecoder<ArrayOfNullableInt>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ArrayOfNullableInt> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ArrayOfNullableInt> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ArrayOfNullableInt> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ArrayOfNullableInt>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ArrayOfNullableInt to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ArrayOfNullableInt from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ArrayOfNullableInt instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ArrayOfNullableInt fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<java.lang.Integer> values;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ArrayOfNullableInt() {}

  /**
   * All-args constructor.
   * @param values The new value for values
   */
  public ArrayOfNullableInt(java.util.List<java.lang.Integer> values) {
    this.values = values;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return values;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: values = (java.util.List<java.lang.Integer>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'values' field.
   * @return The value of the 'values' field.
   */
  public java.util.List<java.lang.Integer> getValues() {
    return values;
  }


  /**
   * Sets the value of the 'values' field.
   * @param value the value to set.
   */
  public void setValues(java.util.List<java.lang.Integer> value) {
    this.values = value;
  }

  /**
   * Creates a new ArrayOfNullableInt RecordBuilder.
   * @return A new ArrayOfNullableInt RecordBuilder
   */
  public static Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder newBuilder() {
    return new Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder();
  }

  /**
   * Creates a new ArrayOfNullableInt RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ArrayOfNullableInt RecordBuilder
   */
  public static Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder newBuilder(Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder other) {
    if (other == null) {
      return new Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder();
    } else {
      return new Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder(other);
    }
  }

  /**
   * Creates a new ArrayOfNullableInt RecordBuilder by copying an existing ArrayOfNullableInt instance.
   * @param other The existing instance to copy.
   * @return A new ArrayOfNullableInt RecordBuilder
   */
  public static Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder newBuilder(Energistics.Etp.v12.Datatypes.ArrayOfNullableInt other) {
    if (other == null) {
      return new Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder();
    } else {
      return new Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder(other);
    }
  }

  /**
   * RecordBuilder for ArrayOfNullableInt instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ArrayOfNullableInt>
    implements org.apache.avro.data.RecordBuilder<ArrayOfNullableInt> {

    private java.util.List<java.lang.Integer> values;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.values)) {
        this.values = data().deepCopy(fields()[0].schema(), other.values);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing ArrayOfNullableInt instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Etp.v12.Datatypes.ArrayOfNullableInt other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.values)) {
        this.values = data().deepCopy(fields()[0].schema(), other.values);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'values' field.
      * @return The value.
      */
    public java.util.List<java.lang.Integer> getValues() {
      return values;
    }


    /**
      * Sets the value of the 'values' field.
      * @param value The value of 'values'.
      * @return This builder.
      */
    public Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder setValues(java.util.List<java.lang.Integer> value) {
      validate(fields()[0], value);
      this.values = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'values' field has been set.
      * @return True if the 'values' field has been set, false otherwise.
      */
    public boolean hasValues() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'values' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.Datatypes.ArrayOfNullableInt.Builder clearValues() {
      values = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ArrayOfNullableInt build() {
      try {
        ArrayOfNullableInt record = new ArrayOfNullableInt();
        record.values = fieldSetFlags()[0] ? this.values : (java.util.List<java.lang.Integer>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ArrayOfNullableInt>
    WRITER$ = (org.apache.avro.io.DatumWriter<ArrayOfNullableInt>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ArrayOfNullableInt>
    READER$ = (org.apache.avro.io.DatumReader<ArrayOfNullableInt>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.values.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.Integer e0: this.values) {
      actualSize0++;
      out.startItem();
      if (e0 == null) {
        out.writeIndex(0);
        out.writeNull();
      } else {
        out.writeIndex(1);
        out.writeInt(e0);
      }
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<java.lang.Integer> a0 = this.values;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.Integer>((int)size0, SCHEMA$.getField("values").schema());
        this.values = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.Integer> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Integer>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.Integer e0 = (ga0 != null ? ga0.peek() : null);
          if (in.readIndex() != 1) {
            in.readNull();
            e0 = null;
          } else {
            e0 = in.readInt();
          }
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.Integer> a0 = this.values;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.Integer>((int)size0, SCHEMA$.getField("values").schema());
            this.values = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.Integer> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Integer>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.Integer e0 = (ga0 != null ? ga0.peek() : null);
              if (in.readIndex() != 1) {
                in.readNull();
                e0 = null;
              } else {
                e0 = in.readInt();
              }
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










