/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.PrivateProtocols.WitsmlSoap;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WMLS_GetBaseMsg extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -340058200487704667L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WMLS_GetBaseMsg\",\"namespace\":\"Energistics.Etp.v12.PrivateProtocols.WitsmlSoap\",\"fields\":[{\"name\":\"ReturnValueIn\",\"type\":\"int\"}],\"protocol\":\"2100\",\"messageType\":\"5\",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WMLS_GetBaseMsg> ENCODER =
      new BinaryMessageEncoder<WMLS_GetBaseMsg>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WMLS_GetBaseMsg> DECODER =
      new BinaryMessageDecoder<WMLS_GetBaseMsg>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WMLS_GetBaseMsg> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WMLS_GetBaseMsg> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WMLS_GetBaseMsg> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WMLS_GetBaseMsg>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WMLS_GetBaseMsg to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WMLS_GetBaseMsg from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WMLS_GetBaseMsg instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WMLS_GetBaseMsg fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int ReturnValueIn;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WMLS_GetBaseMsg() {}

  /**
   * All-args constructor.
   * @param ReturnValueIn The new value for ReturnValueIn
   */
  public WMLS_GetBaseMsg(java.lang.Integer ReturnValueIn) {
    this.ReturnValueIn = ReturnValueIn;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ReturnValueIn;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ReturnValueIn = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ReturnValueIn' field.
   * @return The value of the 'ReturnValueIn' field.
   */
  public int getReturnValueIn() {
    return ReturnValueIn;
  }


  /**
   * Sets the value of the 'ReturnValueIn' field.
   * @param value the value to set.
   */
  public void setReturnValueIn(int value) {
    this.ReturnValueIn = value;
  }

  /**
   * Creates a new WMLS_GetBaseMsg RecordBuilder.
   * @return A new WMLS_GetBaseMsg RecordBuilder
   */
  public static Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder newBuilder() {
    return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder();
  }

  /**
   * Creates a new WMLS_GetBaseMsg RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WMLS_GetBaseMsg RecordBuilder
   */
  public static Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder newBuilder(Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder other) {
    if (other == null) {
      return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder();
    } else {
      return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder(other);
    }
  }

  /**
   * Creates a new WMLS_GetBaseMsg RecordBuilder by copying an existing WMLS_GetBaseMsg instance.
   * @param other The existing instance to copy.
   * @return A new WMLS_GetBaseMsg RecordBuilder
   */
  public static Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder newBuilder(Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg other) {
    if (other == null) {
      return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder();
    } else {
      return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder(other);
    }
  }

  /**
   * RecordBuilder for WMLS_GetBaseMsg instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WMLS_GetBaseMsg>
    implements org.apache.avro.data.RecordBuilder<WMLS_GetBaseMsg> {

    private int ReturnValueIn;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ReturnValueIn)) {
        this.ReturnValueIn = data().deepCopy(fields()[0].schema(), other.ReturnValueIn);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing WMLS_GetBaseMsg instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ReturnValueIn)) {
        this.ReturnValueIn = data().deepCopy(fields()[0].schema(), other.ReturnValueIn);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'ReturnValueIn' field.
      * @return The value.
      */
    public int getReturnValueIn() {
      return ReturnValueIn;
    }


    /**
      * Sets the value of the 'ReturnValueIn' field.
      * @param value The value of 'ReturnValueIn'.
      * @return This builder.
      */
    public Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder setReturnValueIn(int value) {
      validate(fields()[0], value);
      this.ReturnValueIn = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ReturnValueIn' field has been set.
      * @return True if the 'ReturnValueIn' field has been set, false otherwise.
      */
    public boolean hasReturnValueIn() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ReturnValueIn' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_GetBaseMsg.Builder clearReturnValueIn() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WMLS_GetBaseMsg build() {
      try {
        WMLS_GetBaseMsg record = new WMLS_GetBaseMsg();
        record.ReturnValueIn = fieldSetFlags()[0] ? this.ReturnValueIn : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WMLS_GetBaseMsg>
    WRITER$ = (org.apache.avro.io.DatumWriter<WMLS_GetBaseMsg>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WMLS_GetBaseMsg>
    READER$ = (org.apache.avro.io.DatumReader<WMLS_GetBaseMsg>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.ReturnValueIn);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ReturnValueIn = in.readInt();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ReturnValueIn = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










