/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.PrivateProtocols.WitsmlSoap;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WMLS_AddToStoreResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6818125120468552848L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WMLS_AddToStoreResponse\",\"namespace\":\"Energistics.Etp.v12.PrivateProtocols.WitsmlSoap\",\"fields\":[{\"name\":\"Result\",\"type\":\"int\"},{\"name\":\"SuppMsgOut\",\"type\":\"string\"}],\"protocol\":\"2100\",\"messageType\":\"2\",\"senderRole\":\"store\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WMLS_AddToStoreResponse> ENCODER =
      new BinaryMessageEncoder<WMLS_AddToStoreResponse>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WMLS_AddToStoreResponse> DECODER =
      new BinaryMessageDecoder<WMLS_AddToStoreResponse>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WMLS_AddToStoreResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WMLS_AddToStoreResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WMLS_AddToStoreResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WMLS_AddToStoreResponse>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WMLS_AddToStoreResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WMLS_AddToStoreResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WMLS_AddToStoreResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WMLS_AddToStoreResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int Result;
   private java.lang.CharSequence SuppMsgOut;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WMLS_AddToStoreResponse() {}

  /**
   * All-args constructor.
   * @param Result The new value for Result
   * @param SuppMsgOut The new value for SuppMsgOut
   */
  public WMLS_AddToStoreResponse(java.lang.Integer Result, java.lang.CharSequence SuppMsgOut) {
    this.Result = Result;
    this.SuppMsgOut = SuppMsgOut;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Result;
    case 1: return SuppMsgOut;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Result = (java.lang.Integer)value$; break;
    case 1: SuppMsgOut = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Result' field.
   * @return The value of the 'Result' field.
   */
  public int getResult() {
    return Result;
  }


  /**
   * Sets the value of the 'Result' field.
   * @param value the value to set.
   */
  public void setResult(int value) {
    this.Result = value;
  }

  /**
   * Gets the value of the 'SuppMsgOut' field.
   * @return The value of the 'SuppMsgOut' field.
   */
  public java.lang.CharSequence getSuppMsgOut() {
    return SuppMsgOut;
  }


  /**
   * Sets the value of the 'SuppMsgOut' field.
   * @param value the value to set.
   */
  public void setSuppMsgOut(java.lang.CharSequence value) {
    this.SuppMsgOut = value;
  }

  /**
   * Creates a new WMLS_AddToStoreResponse RecordBuilder.
   * @return A new WMLS_AddToStoreResponse RecordBuilder
   */
  public static Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder newBuilder() {
    return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder();
  }

  /**
   * Creates a new WMLS_AddToStoreResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WMLS_AddToStoreResponse RecordBuilder
   */
  public static Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder newBuilder(Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder other) {
    if (other == null) {
      return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder();
    } else {
      return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder(other);
    }
  }

  /**
   * Creates a new WMLS_AddToStoreResponse RecordBuilder by copying an existing WMLS_AddToStoreResponse instance.
   * @param other The existing instance to copy.
   * @return A new WMLS_AddToStoreResponse RecordBuilder
   */
  public static Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder newBuilder(Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse other) {
    if (other == null) {
      return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder();
    } else {
      return new Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for WMLS_AddToStoreResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WMLS_AddToStoreResponse>
    implements org.apache.avro.data.RecordBuilder<WMLS_AddToStoreResponse> {

    private int Result;
    private java.lang.CharSequence SuppMsgOut;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Result)) {
        this.Result = data().deepCopy(fields()[0].schema(), other.Result);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.SuppMsgOut)) {
        this.SuppMsgOut = data().deepCopy(fields()[1].schema(), other.SuppMsgOut);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing WMLS_AddToStoreResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.Result)) {
        this.Result = data().deepCopy(fields()[0].schema(), other.Result);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.SuppMsgOut)) {
        this.SuppMsgOut = data().deepCopy(fields()[1].schema(), other.SuppMsgOut);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'Result' field.
      * @return The value.
      */
    public int getResult() {
      return Result;
    }


    /**
      * Sets the value of the 'Result' field.
      * @param value The value of 'Result'.
      * @return This builder.
      */
    public Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder setResult(int value) {
      validate(fields()[0], value);
      this.Result = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Result' field has been set.
      * @return True if the 'Result' field has been set, false otherwise.
      */
    public boolean hasResult() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Result' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder clearResult() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'SuppMsgOut' field.
      * @return The value.
      */
    public java.lang.CharSequence getSuppMsgOut() {
      return SuppMsgOut;
    }


    /**
      * Sets the value of the 'SuppMsgOut' field.
      * @param value The value of 'SuppMsgOut'.
      * @return This builder.
      */
    public Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder setSuppMsgOut(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.SuppMsgOut = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'SuppMsgOut' field has been set.
      * @return True if the 'SuppMsgOut' field has been set, false otherwise.
      */
    public boolean hasSuppMsgOut() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'SuppMsgOut' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.PrivateProtocols.WitsmlSoap.WMLS_AddToStoreResponse.Builder clearSuppMsgOut() {
      SuppMsgOut = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WMLS_AddToStoreResponse build() {
      try {
        WMLS_AddToStoreResponse record = new WMLS_AddToStoreResponse();
        record.Result = fieldSetFlags()[0] ? this.Result : (java.lang.Integer) defaultValue(fields()[0]);
        record.SuppMsgOut = fieldSetFlags()[1] ? this.SuppMsgOut : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WMLS_AddToStoreResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<WMLS_AddToStoreResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WMLS_AddToStoreResponse>
    READER$ = (org.apache.avro.io.DatumReader<WMLS_AddToStoreResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.Result);

    out.writeString(this.SuppMsgOut);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.Result = in.readInt();

      this.SuppMsgOut = in.readString(this.SuppMsgOut instanceof Utf8 ? (Utf8)this.SuppMsgOut : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.Result = in.readInt();
          break;

        case 1:
          this.SuppMsgOut = in.readString(this.SuppMsgOut instanceof Utf8 ? (Utf8)this.SuppMsgOut : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










