/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.Protocol.Store;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeleteDataObjectsResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7398116001780240931L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeleteDataObjectsResponse\",\"namespace\":\"Energistics.Etp.v12.Protocol.Store\",\"fields\":[{\"name\":\"deletedUris\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"ArrayOfString\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfString\",\"depends\":[]}}}],\"protocol\":\"4\",\"messageType\":\"10\",\"senderRole\":\"store\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":true,\"fullName\":\"Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse\",\"depends\":[\"Energistics.Etp.v12.Datatypes.ArrayOfString\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeleteDataObjectsResponse> ENCODER =
      new BinaryMessageEncoder<DeleteDataObjectsResponse>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeleteDataObjectsResponse> DECODER =
      new BinaryMessageDecoder<DeleteDataObjectsResponse>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeleteDataObjectsResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeleteDataObjectsResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeleteDataObjectsResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DeleteDataObjectsResponse>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeleteDataObjectsResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeleteDataObjectsResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeleteDataObjectsResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeleteDataObjectsResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString> deletedUris;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeleteDataObjectsResponse() {}

  /**
   * All-args constructor.
   * @param deletedUris The new value for deletedUris
   */
  public DeleteDataObjectsResponse(java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString> deletedUris) {
    this.deletedUris = deletedUris;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deletedUris;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deletedUris = (java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'deletedUris' field.
   * @return The value of the 'deletedUris' field.
   */
  public java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString> getDeletedUris() {
    return deletedUris;
  }


  /**
   * Sets the value of the 'deletedUris' field.
   * @param value the value to set.
   */
  public void setDeletedUris(java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString> value) {
    this.deletedUris = value;
  }

  /**
   * Creates a new DeleteDataObjectsResponse RecordBuilder.
   * @return A new DeleteDataObjectsResponse RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder newBuilder() {
    return new Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder();
  }

  /**
   * Creates a new DeleteDataObjectsResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeleteDataObjectsResponse RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder newBuilder(Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder other) {
    if (other == null) {
      return new Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder();
    } else {
      return new Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder(other);
    }
  }

  /**
   * Creates a new DeleteDataObjectsResponse RecordBuilder by copying an existing DeleteDataObjectsResponse instance.
   * @param other The existing instance to copy.
   * @return A new DeleteDataObjectsResponse RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder newBuilder(Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse other) {
    if (other == null) {
      return new Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder();
    } else {
      return new Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeleteDataObjectsResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeleteDataObjectsResponse>
    implements org.apache.avro.data.RecordBuilder<DeleteDataObjectsResponse> {

    private java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString> deletedUris;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deletedUris)) {
        this.deletedUris = data().deepCopy(fields()[0].schema(), other.deletedUris);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing DeleteDataObjectsResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.deletedUris)) {
        this.deletedUris = data().deepCopy(fields()[0].schema(), other.deletedUris);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'deletedUris' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString> getDeletedUris() {
      return deletedUris;
    }


    /**
      * Sets the value of the 'deletedUris' field.
      * @param value The value of 'deletedUris'.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder setDeletedUris(java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString> value) {
      validate(fields()[0], value);
      this.deletedUris = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deletedUris' field has been set.
      * @return True if the 'deletedUris' field has been set, false otherwise.
      */
    public boolean hasDeletedUris() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deletedUris' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.Store.DeleteDataObjectsResponse.Builder clearDeletedUris() {
      deletedUris = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeleteDataObjectsResponse build() {
      try {
        DeleteDataObjectsResponse record = new DeleteDataObjectsResponse();
        record.deletedUris = fieldSetFlags()[0] ? this.deletedUris : (java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeleteDataObjectsResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeleteDataObjectsResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeleteDataObjectsResponse>
    READER$ = (org.apache.avro.io.DatumReader<DeleteDataObjectsResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.deletedUris.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, Energistics.Etp.v12.Datatypes.ArrayOfString> e0: this.deletedUris.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      Energistics.Etp.v12.Datatypes.ArrayOfString v0 = e0.getValue();
      v0.customEncode(out);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString> m0 = this.deletedUris; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString>((int)size0);
        this.deletedUris = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence k0 = null;
          k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
          Energistics.Etp.v12.Datatypes.ArrayOfString v0 = null;
          if (v0 == null) {
            v0 = new Energistics.Etp.v12.Datatypes.ArrayOfString();
          }
          v0.customDecode(in);
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString> m0 = this.deletedUris; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.CharSequence,Energistics.Etp.v12.Datatypes.ArrayOfString>((int)size0);
            this.deletedUris = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence k0 = null;
              k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
              Energistics.Etp.v12.Datatypes.ArrayOfString v0 = null;
              if (v0 == null) {
                v0 = new Energistics.Etp.v12.Datatypes.ArrayOfString();
              }
              v0.customDecode(in);
              m0.put(k0, v0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










