/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Etp.v12.Protocol.Dataspace;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GetDataspaces extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7621409480701539215L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GetDataspaces\",\"namespace\":\"Energistics.Etp.v12.Protocol.Dataspace\",\"fields\":[{\"name\":\"storeLastWriteFilter\",\"type\":[\"null\",\"long\"]}],\"protocol\":\"24\",\"messageType\":\"1\",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces\",\"depends\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GetDataspaces> ENCODER =
      new BinaryMessageEncoder<GetDataspaces>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GetDataspaces> DECODER =
      new BinaryMessageDecoder<GetDataspaces>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GetDataspaces> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GetDataspaces> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GetDataspaces> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GetDataspaces>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GetDataspaces to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GetDataspaces from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GetDataspaces instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GetDataspaces fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long storeLastWriteFilter;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GetDataspaces() {}

  /**
   * All-args constructor.
   * @param storeLastWriteFilter The new value for storeLastWriteFilter
   */
  public GetDataspaces(java.lang.Long storeLastWriteFilter) {
    this.storeLastWriteFilter = storeLastWriteFilter;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return storeLastWriteFilter;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: storeLastWriteFilter = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'storeLastWriteFilter' field.
   * @return The value of the 'storeLastWriteFilter' field.
   */
  public java.lang.Long getStoreLastWriteFilter() {
    return storeLastWriteFilter;
  }


  /**
   * Sets the value of the 'storeLastWriteFilter' field.
   * @param value the value to set.
   */
  public void setStoreLastWriteFilter(java.lang.Long value) {
    this.storeLastWriteFilter = value;
  }

  /**
   * Creates a new GetDataspaces RecordBuilder.
   * @return A new GetDataspaces RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder newBuilder() {
    return new Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder();
  }

  /**
   * Creates a new GetDataspaces RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GetDataspaces RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder newBuilder(Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder other) {
    if (other == null) {
      return new Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder();
    } else {
      return new Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder(other);
    }
  }

  /**
   * Creates a new GetDataspaces RecordBuilder by copying an existing GetDataspaces instance.
   * @param other The existing instance to copy.
   * @return A new GetDataspaces RecordBuilder
   */
  public static Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder newBuilder(Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces other) {
    if (other == null) {
      return new Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder();
    } else {
      return new Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder(other);
    }
  }

  /**
   * RecordBuilder for GetDataspaces instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GetDataspaces>
    implements org.apache.avro.data.RecordBuilder<GetDataspaces> {

    private java.lang.Long storeLastWriteFilter;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.storeLastWriteFilter)) {
        this.storeLastWriteFilter = data().deepCopy(fields()[0].schema(), other.storeLastWriteFilter);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing GetDataspaces instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.storeLastWriteFilter)) {
        this.storeLastWriteFilter = data().deepCopy(fields()[0].schema(), other.storeLastWriteFilter);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'storeLastWriteFilter' field.
      * @return The value.
      */
    public java.lang.Long getStoreLastWriteFilter() {
      return storeLastWriteFilter;
    }


    /**
      * Sets the value of the 'storeLastWriteFilter' field.
      * @param value The value of 'storeLastWriteFilter'.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder setStoreLastWriteFilter(java.lang.Long value) {
      validate(fields()[0], value);
      this.storeLastWriteFilter = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'storeLastWriteFilter' field has been set.
      * @return True if the 'storeLastWriteFilter' field has been set, false otherwise.
      */
    public boolean hasStoreLastWriteFilter() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'storeLastWriteFilter' field.
      * @return This builder.
      */
    public Energistics.Etp.v12.Protocol.Dataspace.GetDataspaces.Builder clearStoreLastWriteFilter() {
      storeLastWriteFilter = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GetDataspaces build() {
      try {
        GetDataspaces record = new GetDataspaces();
        record.storeLastWriteFilter = fieldSetFlags()[0] ? this.storeLastWriteFilter : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GetDataspaces>
    WRITER$ = (org.apache.avro.io.DatumWriter<GetDataspaces>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GetDataspaces>
    READER$ = (org.apache.avro.io.DatumReader<GetDataspaces>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.storeLastWriteFilter == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.storeLastWriteFilter);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.storeLastWriteFilter = null;
      } else {
        this.storeLastWriteFilter = in.readLong();
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.storeLastWriteFilter = null;
          } else {
            this.storeLastWriteFilter = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










